text = "TAATTCAGCCTACCCTGCCTCGTCGTCGAGTGCGCCCCTTCAGAAGACATCATGCTCTTTGTGCTACGGGCGTTAGCTTTCGGACGGAATAAGAGTCAGTGCTATTTGCAAGGGGTCGAGCTTCCGTCCGCGGATTAAACGTGACTGCGGATGTACGCTCAGACAGGTCGGAATTCGTGCTCACCAGGGGTCATCGGTTTCAGCTGCGCTAAACCATTAGATAGGTTCACTCCCTCGGAGGAGGGAACAGACATTTATTATAAAGGTTTTACCGGAGACCAAGAGCGACTAACGACGAAAGTTTCAAACGTCGTAAAAATCAAACTAGACGGATGCCGTTGCGACCAGACGACCGGGGCACTCTTTATAAGAGTTTAGCTTGCGCTCAGCGCCGGTCCACTACGCGTGGACGCAAATGTACGATTGGATGCGAGTTTCAGGGCCAAATCTTCTCATGCATTATCGATACCTGGAGTCCCTAGAATCCAGATCAGACGAACCACCGAGACATTGTCAGCTACGCCATGAAACTATAAACGACACGTTTTCTTGGTGGGCGCTTTTCGGCCTCGCACACTCCTAATCACGGCGTCTCTCCTGCATAGTAGTTGATGCCGGCAGGCCTGGTGTCATTGGGACTCAGGGTTGATATGAGGGCTGAATTCGGCGACCGGTGTCCCCAGCAAGTGTTGATAGGGAGTATTACCATGCCTCATGGCCGTCCCCCGTTTACTAAGAGGCAGTGTAGGATTAACCACAAGCGGACTACTTCATGGGCTGTTCCAACATCCAGAGGCGGTCCGCTCGTCAACGCGTAGTAGGCGCATTAGCCCATCTCCAGACCCTCAGAGC"
text_reverse = text[::-1]
output = ""
for i in text_reverse:
    if i == "A":
        output = output + "T"
    if i == "T":
        output = output + "A"
    if i == "C":
        output = output + "G"
    if i == "G":
        output = output + "C"
    
print(output)